<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $table = 'messages';

    protected $fillable = ['from_user_id','to_user_id','body','dialog_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function fromUser()
    {
        return $this->belongsTo(User::class,'from_user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function toUser()
    {
        return $this->belongsTo(User::class,'to_user_id');
    }


    public function markAsRead()
    {
        if (is_null($this->read_at))
        {
            // 在表中修改填充数据
            $this->forceFill(['is_read' => 'T','read_at' => $this->freshTimestamp()])->save();
        }

    }

    // 这是laravel提供的便利 让我们可以执行collection组合中对象的方法 不然我们不能执行
    public function newCollection(array $models = [])
    {
        return new MessageCollection($models); // TODO: Change the autogenerated stub
    }


}
